version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./volume/mysql:/var/lib/mysql
